name: Hola Mundo 1

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo..."
      
    - name: touch file
      run: touch file.txt

    - name: Set text
      run: echo "Hola Mundo..." >> hola.txt

    - name: Red file
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: LS
      run: ls -al
    - name: ls
      run: | 
        chmod +x script.sh
        ./script.sh
